// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrYNmkDB9eGaLoWT8Tb2izpgt1XvcQnw8',
    appId: '1:1013781944564:web:5fc42bf69d26222ee566a1',
    messagingSenderId: '1013781944564',
    projectId: 'pasien-b76d3',
    authDomain: 'pasien-b76d3.firebaseapp.com',
    storageBucket: 'pasien-b76d3.appspot.com',
    measurementId: 'G-1HRC3PE1W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD5yeuHcd2DjWn5WhN28b_qrBiUnjAZ0U',
    appId: '1:1013781944564:android:b8f0b65e384fe46de566a1',
    messagingSenderId: '1013781944564',
    projectId: 'pasien-b76d3',
    storageBucket: 'pasien-b76d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXEerIVvXjI2kOOlecfnfPIWjXAfZP3MI',
    appId: '1:1013781944564:ios:180e134327f04fb9e566a1',
    messagingSenderId: '1013781944564',
    projectId: 'pasien-b76d3',
    storageBucket: 'pasien-b76d3.appspot.com',
    iosBundleId: 'com.example.rumahSakit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXEerIVvXjI2kOOlecfnfPIWjXAfZP3MI',
    appId: '1:1013781944564:ios:180e134327f04fb9e566a1',
    messagingSenderId: '1013781944564',
    projectId: 'pasien-b76d3',
    storageBucket: 'pasien-b76d3.appspot.com',
    iosBundleId: 'com.example.rumahSakit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrYNmkDB9eGaLoWT8Tb2izpgt1XvcQnw8',
    appId: '1:1013781944564:web:47ef82d8c40b36c0e566a1',
    messagingSenderId: '1013781944564',
    projectId: 'pasien-b76d3',
    authDomain: 'pasien-b76d3.firebaseapp.com',
    storageBucket: 'pasien-b76d3.appspot.com',
    measurementId: 'G-90SQKDRMHR',
  );
}
